# [Cannot use underscore and period in name of application]
application: comment-1213
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

# Using static files
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: allow_comment.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
